---
collections:
- name: cisco.ios
  version: 2.0.1
- name: cisco.asa
- name: servicenow.itsm
- name: servicenow.servicenow
- name: ansible.tower
- name: ansible.controller
- name: chocolatey.chocolatey
- name: azure.azcollection
- name: community.docker
- name: community.general
- name: amazon.aws
- name: dynatrace.oneagent
  source: https://kzn34165.live.dynatrace.com/rest/deployment/orchestration/agent/ansible/latest?arch=x86&flavor=default
  type: file
