---
collections:
- name: cisco.ios
  version: 2.0.1
- name: cisco.asa
- name: servicenow.itsm
- name: servicenow.servicenow
- name: ansible.tower
- name: ansible.controller
- name: chocolatey.chocolatey
- name: azure.azcollection
- name: community.docker
- name: community.general
- name: amazon.aws
- source: http://172.16.1.25:8080/dynatrace-oneagent-ansible-1.1.0.20211006-104525.tar.gz
  name: dynatrace.oneagent
