---
collections:
- name: cisco.ios
  version: 2.0.1
- name: cisco.asa
- name: servicenow.itsm
- name: servicenow.servicenow
- name: ansible.tower
- name: chocolatey.chocolatey
- name: azure.azcollection
- name: community.docker
- name: community.general
