---
- name: Install or remove IIS
  hosts: all
  gather_facts: true

  tasks:
    - name: "{{ iis_state }}" IIS Web Server
      win_feature:
        name: Web-Server
        state: "{{ iis_state }}"
