---
- name: Install or remove IIS
  hosts: all
  gather_facts: true

  tasks:
    - name: Updateing IIS Web Server to {{ iis_state }}
      win_feature:
        name: Web-Server
        state: "{{ iis_state }}"
