---
- name: Get min facts
  hosts: all
  gather_facts: False
  tasks:
    - name: Gathering facts
      setup:
        gather_subset:
           - '!all'
           - '!any'
           - min
      register: register_output
    - name: Display Register
      debug:
        msg: "{{ register_output }}"
