- name: Create a resource group {{az_rgname}}
  azure_rm_resourcegroup:
    name: "{{ cloud_name }}"
    location: "{{ region }}"
    tags:
      created: ansbile
      delete: never
      demo: "{{ customer }}"
- include: createsubnet.yml
