---
- hosts: all
  gather_facts: no
  tasks:
    - name: Ping retries test
      ping:
      register: result
      until: result.ping == 'pong'
      retries: 10
      delay: 50
    - name: wait_for_connection
      wait_for_connection:
        delay: 30
        sleep: 10
        timeout: 600
      delegate_to: localhost
