---
- name: Get Service info
  hosts: all
  gather_facts: False
  tasks:
    - name: Query Service Request Template for RHPDS Tasks
      uri:
        url: "{{ rhpdsurl }}/api/v3.0.0/service_requests/{{serviceid}}?expand=request_tasks"
        user: "{{ rhpdsuser }}"
        password: "{{ rhpdspass }}"
        method: GET
      register: serviceexpanded
    #- name: Show all output
    #  debug:
    #    msg: "{{serviceexpanded}}"

    - name: Task ID
      debug:
        msg: "{{serviceexpanded.json.request_tasks[0].id}}"
    - name: Task URI request
      debug:
        msg: "{{serviceexpanded.json.request_tasks[0].href}}"
    - name: Query Service Template for (ServiceID)
      uri:
        url: "{{ serviceexpanded.json.request_tasks[0].href }}"
        user: "{{ rhpdsuser }}"
        password: "{{ rhpdspass }}"
        method: GET
      register: taskinformation
    #- name: Task options
    #  debug:
    #    msg: "{{taskinformation.json.options.dialog}}"
    - name: Service ID
      debug:
        msg: "{{taskinformation.json.options.dialog['Service::Service']}}"
    - name: Query Service {{taskinformation.json.options.dialog['Service::Service']}} for Custom Attributes)
      uri:
        url: "{{ rhpdsurl }}/api/v3.0.0/services/{{taskinformation.json.options.dialog['Service::Service']}}?attributes=custom_attributes"
        user: "{{ rhpdsuser }}"
        password: "{{ rhpdspass }}"
        method: GET
      register: moreattributes
    - name: Searching project for custom field gid
      vars:
        _query: "msg[?name ==`uuid`].value"
      set_fact:
        aws_access_key: "{{ moreattributes.json.custom_attributes|json_query(_query) }}"
    - name:
      debug: msg="{{moreattributes.json.custom_attributes|json_query(jquery)}}"
      vars:
        jquery: "[?name ==`uuid`].value"
