---
- name: Gather fact ESXi host
  hosts: localhost
  vars:
     ansible_python_interpreter: "/usr/bin/env python"
     esxi_server: ''
     esxi_username: ''
     esxi_password: ''
  tasks:
   - name: Gather vmware host facts
     vmware_host_facts:
        hostname: "{{ esxi_server }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
     register: host_facts
   - name: Display Facts
     debug:
       msg: "{{host_facts}}"
