- name: Known Error Demo (batch copy fail)
  hosts: all
  vars:
    host: dev67705.service-now.com
    username: "{{ snow_username }}"
    password: "{{ snow_password }}"


  tasks:

    - name: Retrieve all incidents
      servicenow.itsm.incident_info:
      register: result
