---
- name: Check Firmware Version is Compliant
  hosts: all
  connection: network_cli
  gather_facts: no
  vars:
     message: 'Network Invetory report created http://172.16.1.25:8080/report.html'
     channel: '#toweralerts'

  tasks:
    - name: 'Preflight Varible check :: slack_token'
      fail: msg='Please include the slack_token to the variable "slack_token"'
      run_once: true
      when: 'slack_token is not defined'
    - name: 'Preflight Varible check :: message'
      fail: msg='Please include the message to the variable "message"'
      run_once: true
      when: 'message is not defined'
    - name: 'Preflight Varible check :: channel'
      fail: msg='Please include the slack_token to the variable "channel"'
      run_once: true
      when: 'channel is not defined'


    - name: Send Alert to Slack
      slack:
       token: "{{ slack_token }}"
       msg: "{{ message }}"
       channel: "{{ channel }}"
       username: 'Ansible Tower'
      run_once: true
      delegate_to: localhost
