---
- name: Check Firmware Version is Compliant
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
     compliant_ios_version: ''
     ansible_connection: ''
     ansible_network_os: ''

  tasks:
    - name: Gather Live facts from Device
      ios_facts:
          gather_subset: hardware
