---
- name: Check Firmware Version is Compliant
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
     compliant_ios_version: ''
     ansible_connection: ''
     ansible_network_os: ''


  tasks:
  - name: GATHERING FACTS ON {{inventory_hostname}}
    ios_facts:
    debug:
        msg: "Device {{inventory_hostname}} has IOS {{ansible_net_version}}"

  - name: ASSERT THAT THE IOS VERSION IS {{compliant_ios_version}} CORRECT ON {{inventory_hostname}}
    assert:
      that:
        - compliant_ios_version == ansible_net_version
      msg: "IOS version does not match compliant version. Upgrade please run upgrade Playbook."

    when: ansible_net_version != compliant_ios_version
