---
- name: Check Firmware Version is Compliant
  hosts: all
  connection: network_cli
  gather_facts: no



  tasks:
    - name: Gather Live facts from Device
      ios_facts:
          gather_subset: min



    - name: Checking to see if needs Upgrade
      assert:
        that:
            - compliant_ios_version == ansible_net_version
        msg: "IOS version {{ansible_net_version}} does not match compliant version. Please run Upgrade."
      when: ansible_net_version != compliant_ios_version
      ignore_errors: True
    - name: Send Alert to Slack
      slack:
        msg: 'IOS version {{ansible_net_version}} does not match compliant version on {{inventory_hostname}} Please run Upgrade.'
        channel: '#toweralerts'
        username: 'Ansible on {{ inventory_hostname }}'
      delegate_to: localhost
