
---
- name: Setting Interface Description
  hosts: all
  gather_facts: False
  vars:
    ansible_connection: ''
    ansible_network_os: ''
  tasks:
    - name: get show interface
      ios_command:
        commands:
            - show interface
      register: iface_output

    - name: Debug iface_output
      debug:
        var: {{ iface_output | parse_cli('./parse.txt') }}
