---
- name: IOS inteface facts
  hosts: all
  gather_facts: False
  collections:
   - cisco.ios

  tasks:

  - name: Getting Ios descirptions
    cisco.ios.ios_interfaces:
      config:
      state: gathered
