---
- name: IOS inteface facts
  hosts: all
  gather_facts: False


  tasks:

  - name: Setting Description on {{int_name}} and status {{int_enabled}}
    cisco.ios.ios_interfaces:
      config:
      state: gathered
