---
- name: Configure Vlans
  hosts: ios
  gather_facts: False
  vars:
    ansible_connection: ''
    ansible_network_os: ''
    vlan_name: ''
    vlan_id: ''
    vlan_state: ''
    vlan_shutdown: ''
    module_state: ''

  tasks:
   - name: to devices
     ios_vlans:
       config:
         - name: TEST
           vlan_id: 100
           state: active
           shutdown: enabled
       state: overridden
