---
- name: Show Running Configs
  hosts: all
  gather_facts: False
  vars:
    ansible_connection: ''
    ansible_network_os: ''
    command: ''

  tasks:
    - name: Running {{command}}
      ios_command:
        command: show running-command
      register: config_output
    - debug:
      var: config_output
