---
- name: Show Running Configs
  hosts: all
  gather_facts: False
  vars:
    ansible_connection: ''
    ansible_network_os: ''
  tasks:

  - name: Backup the config
    ios_command:
      commands:
        - show running-config
    register: config_output

  - debug:
      var: config_output
