---
- name: Start Backup of Network Devices
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: ''
    ansible_network_os: ''
    backup_path: ''
    sshkey: ''
    network_backup_dir: "{{ backup_path }}"
    network_backup_file: "{{ network_backup_dir }}/{{ inventory_hostname }}.cfg"

  tasks:
  - name: Clone the backup repo
    git:
      repo: "{{ network_backup_repository }}"
      dest: "{{ network_backup_dir }}"
      accept_hostkey: yes
      key_file: "{{sshkey}}"
      force: yes
    become: true
    become_user: root
    delegate_to: localhost
    register: clone_result
    run_once: true
    when: network_backup_repository is defined


  - include_tasks: "{{ ansible_network_os }}-backup.yml"
  - name: REMOVE NON CONFIG LINES
    lineinfile:
      path: "{{network_backup_dir}}/{{inventory_hostname}}.cfg"
      line: "Building configuration..."
      state: absent

  - name: REMOVE NON CONFIG LINES - REGEXP
    lineinfile:
      path: "{{network_backup_dir}}/{{inventory_hostname}}.cfg"
      regexp: 'Current configuration.*'
      state: absent

  - block:
    - name: Add any new backups to the repossitory
      shell: "git add *.cfg"
      args:
        chdir: "{{ network_backup_dir }}"
      delegate_to: localhost
      changed_when: False
      run_once: true

    - name: Get the status of the repository
      shell: "git status"
      args:
        chdir: "{{ network_backup_dir }}"
      register: status_results
      changed_when: False
      ignore_errors: yes
      delegate_to: localhost
      run_once: true

    - name: Commit the changes
      shell: "git commit -am 'Changed'"
      args:
          chdir: "{{ network_backup_dir }}"
      when: status_results.stdout is search('Changes')
      delegate_to: localhost
      run_once: true
      environment:
        GIT_COMMITTER_NAME: "{{ git_name | default(omit) }}"
        GIT_COMMITTER_EMAIL: "{{ git_email | default(omit) }}"
        GIT_AUTHOR_NAME: "{{ git_name | default(omit) }}"
        GIT_AUTHOR_EMAIL: "{{ git_email | default(omit) }}"

    - name: Push the changes
      git:
        repo: "{{ network_backup_dir }}"
        dest: "{{ network_backup_repository }}"
        accept_hostkey: yes
        key_file: "{{sshkey}}"
        force: yes
      become: true
      become_user: root
      delegate_to: localhost
      when: network_backup_repository is defined
