---
- name: Start Restore of Network Devices
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: ''
    ansible_network_os: "{{ansible_net_system}}"
    backup_path: ''
    network_backup_dir: "{{ backup_path }}"
    network_backup_file: "{{ network_backup_dir }}/{{ inventory_hostname }}.cfg"

  tasks:
    - name: Pull latest Config from Github for {{inventory_hostname}}
      command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no {{network_backup_file}} {{inventory_hostname}}:/{{inventory_hostname}}.cfg
    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.cfg force
