---
# Playbook to test new roles and tags
- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - role: aws_create_vpc
      tags: ['aws']
    - role: azure_create_vpc
      tags: ['azure']
  vars:
     aws_access_key: ''  #provided by tower
     aws_secret_key: ''  #provided by tower
     AZURE_CLIENT_ID: '' #provided by tower
     AZURE_SECRET: ''    #provided by tower
     AZURE_SUBSCRIPTION_ID: ''  #provided by tower
     AZURE_TENANT: ''    #provided by tower
     vpc_name: ''
     vpc_cidr: ''
     region: ''
     user_name: ''
     ansible_group: "{{user_name}}"
     security_group_name: "{{vpc_name}}_SECGRP"
     vpc_subnet_name: "{{vpc_name}}_Subnet"
     rt_name: "{{vpc_name}}_RT_Internet"
     igw_name: "{{vpc_name}}_IGW"
     my_email_address: "{{user_name}}@redhat.com"
     alwaysup: ''
     deleteby: ''
