---
# Playbook to test new roles and tags
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
     aws_access_key: ''  #provided by tower
     aws_secret_key: ''  #provided by tower
     AZURE_CLIENT_ID: '' #provided by tower
     AZURE_SECRET: ''    #provided by tower
     AZURE_SUBSCRIPTION_ID: ''  #provided by tower
     AZURE_TENANT: ''    #provided by tower
     ansible_group: "{{user_name}}"
     security_group_name: "{{vpc_name}}_SECGRP"
     vpc_subnet_name: "{{vpc_name}}_Subnet"
     rt_name: "{{vpc_name}}_RT_Internet"
     igw_name: "{{vpc_name}}_IGW"
     my_email_address: "{{user_name}}@redhat.com"

tasks:
- name: 'Preflight Varible check :: aws_access_key'
  fail: msg='Please include the aws_access_key to the variable "aws_access_key"'
  run_once: true
  when: 'aws_access_key is not defined'
- name: 'Preflight Varible check :: aws_secret_key'
  fail: msg='Please include the aws_secret_key to the variable "aws_secret_key"'
  run_once: true
  when: 'aws_secret_key is not defined'
- name: 'Preflight Varible check :: cloud_name'
  fail: msg='Please include the cloud_name to the variable "cloud_name"'
  run_once: true
  when: 'cloud_name is not defined'
- name: 'Preflight Varible check :: cidr'
  fail: msg='Please include the cidr to the variable "cidr"'
  run_once: true
  when: 'cidr is not defined'
- name: 'Preflight Varible check :: region'
  fail: msg='Please include the aws_access_key to the variable "region"'
  run_once: true
  when: 'region is not defined'
- name: 'Preflight Varible check :: user_name'
  fail: msg='Please include the user_name to the variable "user_name"'
  run_once: true
  when: 'user_name is not defined'
- name: 'Preflight Varible check :: alwaysup'
  fail: msg='Please include the aws_access_key to the variable "alwaysup"'
  run_once: true
  when: 'alwaysup is not defined'
- name: 'Preflight Varible check :: deleteby'
  fail: msg='Please include the user_name to the variable "deleteby"'
  run_once: true
  when: 'deleteby is not defined'
- name: Deploy Azure RG
  include_role:
     name: azure_create_vpc
  tags: ['azure']
- name: Deploy Azure RG
  include_role:
     name: aws_create_vpc
  tags: ['aws']
