---
# Playbook to test new roles and tags
- hosts: localhost
  connection: local
  roles:
    - role: network_backup
      tags: ['network_backup']
#    - role: network_compliance
#      tags: ['netcompliance']
