---
- name: Control the EC2 Instance


  hosts: localhost
  connection: local
  vars:
    instance_id: ''
    ec2_tag: ''

tasks:
  - name: Stopping an EC2 Instance {{ec2_tag}}
    local_action: ec2
    instance_tags:
         Name: '{{ec2_tag}}'
    state: stopped
