---
- name: Backup the config or inventory_hostname
  asa_config:
    backup: yes
    backup_options:
      dir_path: "{{backup_path}}"
      filename: "{{inventory_hostname}}.cfg"
  register: config_output
