---
- name: Backup the config for {{inventory_hostname}} with {{ansible_network_os}}
  ios_config:
    backup: yes
    backup_options:
      dir_path: "{{backup_path}}"
      filename: "{{inventory_hostname}}.cfg"
  register: config_output
