---
- name: Check file diff
  hosts: all
  gather_facts: False


  tasks:
    - name: Grab Repo with source file
      git:
        repo: 'https://b18d504f239d94ceb3019fa719e5f838c5abea45@github.com/redawg/sourcefiles.git'
        dest: /var/tmp
        accept_hostkey: yes
        force: yes
      delegate_to: 127.0.0.1
      run_once: true

    - name: Check for variance in File
      copy:
        src: /var/tmp/hosts
        dest: /etc/hosts
      check_mode: yes
      diff: yes
