---
- name: Check file diff
  hosts: all
  gather_facts: False


  tasks:
    - name: Grab Repo with source file
      git:
        repo: "{{ sourcefilerepo }}"
        dest: /var/tmp
        accept_hostkey: yes
        force: yes
      delegate_to: 127.0.0.1
      run_once: true

    - name: Check for variance in File
      copy:
        src: /var/tmp/passwd
        dest: /etc/passwd
      check_mode: yes
      diff: yes
