---
- name: Check file diff
  hosts: all
  gather_facts: False


  tasks:
    - name: Grab Repo with source file
      git:
        repo: "{{ sourcefilerepo }}"
        dest: /tmp/demo
        accept_hostkey: yes
        force: yes
      delegate_to: 127.0.0.1
      run_once: true

    - name: Check for variance in File
      copy:
        src: /tmp/demo/passwd
        dest: /etc/passwd
      check_mode: yes
      diff: yes
      register : filechanges

    - name: stat check_mode
      stat:
        path: /etc/passwd
      when: filechanges.changed == true
      register: statvar

    - name: print file data to file
      copy:
        content: "{{ lookup('template', './filedata.j2') }}"
        dest: "{{ home_dir }}"/reports/filedata.html
      run_once: True
      delegate_to: "{{ container_host }}"
