---
- hosts: all
  connection: local
  gather_facts: true
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
