---
- name: Register System to Insights
  hosts: all
  gather_facts: False
  command: insights-client --register
  register: register_output
- name: Display Register
     debug:
       msg: "{{ register_output }}"
