---
- hosts: all
  gather_facts: true
  tasks:
    - name: Return OS version to registered my_release variable
      command: yum -y history rollback "last-1"
      register: my_release
    - debug:
        var:  my_release.stdout_lines
      with_items: groups ['ALL']
