---
- name: Set Default Repos for RHEL 7
  hosts: all
  gather_facts: False
  vars:

  tasks:
    - name: Disable htb repo
      yum:
        disablerepo: "*"
    - name: Enable Repos
      yum:
         enablerepo: "rhel-7-server-extras-rpms,rhel-7-server-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.9-rpms"
