---
- name: Set Default Repos for RHEL 7
  hosts: all
  gather_facts: False
  vars:

  tasks:
    - name: Disable rhel-7-server-htb-rpms Repos
      rhsm_repository:
        name: rhel-7-server-htb-rpms
        state: disabled
