---
- name: Set Default Repos for RHEL 7
  hosts: all
  gather_facts: False
  vars:

  tasks:
    - name: Disable all repo
      yum_repository:
        name: rhel-7-server-htb-rpms
        state: absent
      notify: yum-clean-metadata
