---
- name: Set Default Repos for RHEL 7
  hosts: all
  gather_facts: True
  vars:

  tasks:
    - name: Rhel 7 specific Repos
      block:
        - name: Disable rhel-7-server-htb-rpms Repos
          rhsm_repository:
            name: rhel-7-server-htb-rpms
            state: disabled
        - name: Enable rhel-7-server-rpms
          rhsm_repository:
            name: rhel-7-server-rpms
            state: enable
        - name: Enable rhel-7-server-extras-rpm
          rhsm_repository:
            name: rhel-7-server-extras-rpm
            state: enable
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "7"
