---
- name: Subscribe RHEL to Account
  hosts: all
  gather_facts: true
  vars:
     username: ''
     password: ''
     pool_id: ''
     systemrole: "Red Hat Enterprise Server"
     usage: "Dev/Test"
     sla: "Self-Support"

  tasks:
    - name: Subscribing to RHEL account now
      redhat_subscription:
        state: present
        username: "{{username}}"
        password: "{{password}}"
        pool_ids: "{{pool_id}}"
        syspurpose:
          usage: "{{usage}}"
          role: "{{systemrole}}"
          service_level_agreement: "{{sla}}"
          sync: true
    - name: Copy file with owner and permissions
      copy:
        src: /ect/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
