---
- name: Installing requested package
  hosts: all
  gather_facts: False
  vars:
      package: ''
  serial: 1
  tasks:
    - name: Install {{package}}
      yum:
        name: "{{package}}"
        state: present
      notify: slack_alert
  handlers:
    - name: slack_alert
      slack:
        token: "{{ slack_token }}"
        msg: '{{package}} installed on {{inventory_hostname}}'
        channel: '#toweralerts'
        username: 'Ansible Tower'
      when: slack_token is defined
