---
- name: Installing requested package
  hosts: all
  gather_facts: False
  become: yes
  become_method: enable
  vars:
      package: ''
  serial: 1
  tasks:
    - name: Install {{package}}
      yum:
        name: "{{package}}"
        state: present
