---
- name: Create VPC {{ cloud_name }}_{{user_name}} in {{ region }}
  vpc_net:
    name: "{{ cloud_name }}_{{user_name}}"
    cidr_block: "{{ cidr }}"
    region: "{{ region }}"
    state: present

    tags:
      AlwaysUp: "{{ alwaysup }}"
      Name: "{{ user_name }}"
      ansible_group: "{{ ansible_group }}"
      Createdby: Ansible Tower
      Contact: "{{ my_email_address }}"
      DeletebBy: "{{ deleteby }}"
  register: my_vpc
- name: Display my_vpc.vpc.id info for "{{ cloud_name }}_{{ user_name}}"
  debug:
    var: my_vpc.vpc.id

- name: create security group {{ security_group_name }}
  group:
    name: "{{ security_group_name }}"
    description: Security group with rule descriptions created by Ansible
    vpc_id: "{{ my_vpc.vpc.id }}"
    region: "{{ region }}"
    tags:
      AlwaysUp: "{{ alwaysup }}"
      Name: "{{ user_name }}"
      ansible_group: "{{ ansible_group }}"
      Createdby: Ansible Tower
      Contact: "{{ my_email_address }}"
      DeleteBy: "{{ deleteby }}"
    rules:
    - proto: icmp
      from_port: 8 # icmp type, -1 = any type
      to_port:  -1 # icmp subtype, -1 = any subtype
      cidr_ip: 0.0.0.0/0
      rule_desc: allow ping
    - proto: tcp
      ports: 80
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all on port 80
    - proto: tcp
      ports: 22
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all on port 22
  tags:
    - createsecgrp
    - onlyvpc
  register: my_security_group
- name: Create {{ vpc_subnet_name }} subnet
  vpc_subnet:
    state: present
    vpc_id: "{{ my_vpc.vpc.id }}"
    cidr: "{{ cidr }}"
    region: "{{ region }}"
    map_public: yes
    tags:
      AlwaysUp: "{{ alwaysup }}"
      Name: "{{ vpc_subnet_name }}"
      ansible_group: "{{ ansible_group }}"
      Createdby: Ansible Tower
      Contact: "{{ my_email_address }}"
      DeleteBy: "{{ deleteby }}"
  tags:
    - createsubnet
    - onlyvpc
  register: my_vpc_subnet
- name: Create IGW "{{ igw_name }}" for {{ cloud_name }}_{{user_name}}
  vpc_igw:
    vpc_id: "{{ my_vpc.vpc.id }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "{{igw_name}}"
      ansible_group: "{{ ansible_group }}"
      Createdby: Ansible Tower
      Contact: "{{my_email_address}}"
      DeletebBy: "{{deleteby}}"
  tags:
    - createigw
    - onlyvpc
  register: my_igw
#- name: Gather default Route Table ID
#  vpc_route_table_info:
#    region: "{{ region }}"
#    filters:
#      vpc-id: "{{ my_vpc.vpc.id }}"
#  register: vpc_default_route

- name: Create Internet route Table "{{ rt_name }}"
  vpc_route_table:
    vpc_id: "{{ my_vpc.vpc.id }}"
    region: "{{ region }}"
    #route_table_id: "{{ vpc_default_route.route_tables[0].id }}"
    #lookup: id
    tags:
      AlwaysUp: " {{alwaysup}} "
      Name: "{{ rt_name }}"
      ansible_group: "{{ ansible_group }}"
      Createdby: Ansible Tower
      Contact: "{{ my_email_address }}"
      DeleteBy: "{{deleteby}}"
    subnets:
      - "{{ my_vpc_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ my_igw.gateway_id }}"
  tags:
    - creatert
    - onlyvpc
  register: my_route_table
