---
# This playbook contains common plays that will be run on all nodes.
# Gather the start time to use in a later playbook
- name: Record the lamp_time
  ansible.builtin.command:
    cmd: "date '+%H:%M:%S'"
  delegate_to: 127.0.0.1
  register: lamp_time_pre
  run_once: true

# Make the start time available to other playbooks
- name: Capture the lamp_time
  ansible.builtin.set_stats:
    data:
      lamp_time: "{{ lamp_time_pre.stdout }}"
  run_once: true

- name: Install chrony
  yum:
    name: chrony
    state: present
  tags: chrony

- name: Install common dependencies
  yum:
    name:
      - libselinux-python3
      - libsemanage-python3
      - firewalld
      - chrony
    state: installed

- name: Configure chrony file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  tags: chrony
  notify: restart chrony

- name: Start the chronyd service
  service:
    name: chronyd
    state: started
    enabled: yes
  tags: chrony
