---
- name: Create Custom Cred Type in Controller
  hosts: all
  gather_facts: False

  tasks:
    - name: Create Cred Type
      tower_credential_type:
        name: Test
        description: Test cred type playbook creation
        type: cloud
        injectors: {'extra_vars': {'my_ssh_key_file': '{{tower.filename}}'}}
        state: present
        validate_certs: false
