---
- name: Create Custom Cred Type in Controller
  hosts: all
  gather_facts: False

  tasks:
    - name: Test Cred
      tower_credential_type:
        name: Test
        description: Test cred type playbook creation
        kind: cloud
        inputs: {"fields": [{"id": "username","type": "string","label": "Username"},{"id": "my_ssh_key","type": "string","label": "Private Key","secret": true,"multiline": true}]}
        injectors: {'extra_vars': {'my_ssh_key_file': '{%raw} {{tower.filename}} {%endraw%}'}}
        state: present
        validate_certs: false
