---
- name: Query API for Hosts over 90 days
  hosts: localhost
  gather_facts: False


  tasks:
    - name: Query API for hosts
      ansible.builtin.uri:
        url: "{{ controller_hostname }}/api/v2/hosts"
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        method: GET
        validate_certs: no
      register: allhosts
    - name: Debug allhost
      ansible.builtin.debug:
        var: allhosts


    - name: Add Query to Host list
      ansible.builtin.set_fact:
        allhosts: " {{ allhosts +
                     [{ 'id' : hostid }] }} "
      loop: "{{ id }}"

    - name: Debug allhost
      ansible.builtin.debug:
        var: allhosts
