---
- name: Query API for Hosts over 90 days
  hosts: localhost
  gather_facts: False


  tasks:
    - name: Query API for hosts
      ansible.builtin.uri:
        url: https://172.16.1.24/api/v2/hosts
        user: "{{ controller_username }}"
        password: "{{ controller_password}}"
        force_basic_auth: yes
        method: GET
        validate_certs: no
      register: json_content
    - name: Show json_query
      debug:
        msg: "{{ json_content }}"

    - name: Hostnames and last action
      debug: msg= "{{ json_content.json.results | json_query(jmesquery) }}"
      vars:
         jmesquery: "[*].name"}
