---
- name: Query API for Hosts over 90 days
  hosts: localhost
  gather_facts: False


  tasks:
    - name: Query API for hosts
      ansible.builtin.uri:
        url: https://172.16.1.24/api/v2/hosts
        user: 'admin'
        password: 'r3dh2t!'
        force_basic_auth: yes
        return_content: yes
        method: GET
        validate_certs: no
      register: json_content

    - name: Hostnames and last action
      vars:
        _jquery: "results[*].{Name: name , Last_job_run: summary_fields.last_job.finished , InventoyID: summary_fields.inventory.id, InventoryName: summary_fields.inventory.name  }"
      debug: msg="{{ json_content.json | json_query(_jquery)}}"
