---
- name: Query API for Hosts over 90 days
  hosts: localhost
  gather_facts: False


  tasks:
    - name: Query API for hosts
      ansible.builtin.uri:
        url: https://172.16.1.24/api/v2/hosts
        user: 'admin'
        password: 'r3dh2t!'
        force_basic_auth: yes
        method: GET
        validate_certs: no
      register: jsoncontent

    - name: Hostnames and last action
      debug: msg= "{{ jsoncontent.json | json_query(jmesquery) }}"
      vars:
         jmesquery: "[*]. {ID: id, Name: name}"
