- name: Run cluster recover actions
  hosts: localhost
  connection: local
  gather_facts: False
  become: no
  tasks:
  - name: Wait 3 minutes for Nodes to settle and pods to start
    pause:
      minutes: 3

  - name: Get CSRs that need to be approved
    k8s_facts:
      api_version: certificates.k8s.io/v1beta1
      kind: CertificateSigningRequest
    register: r_csrs

  - when: r_csrs.resources | length > 0
    name: Approve all Pending CSRs
    command: "oc adm certificate approve {{ item.metadata.name }}"
    # when: item.status.conditions[0].type == "Pending"
    loop: "{{ r_csrs.resources }}"
