---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    ansible_connection: ''
    ansible_network_os: ''
    network_backup_dir: "{{ backup_path }}"
    network_backup_file: "{{ network_backup_dir }}/{{ inventory_hostname }}.cfg"

  tasks:
  - name: Compare Backupfile to running-config for {{inventory_hostname}}
    ios_config:
      diff_against: running
      src: {{network_backup_file}}
    register: test_diff

  - name: the only config we need to merge on {{inventory_hostname}} is
    debug:
      var: test_diff.updates
