---
- name: Download OneAgent installer in specific version to a custom

  hosts: all


  tasks:
    - name: Grab oneagent from instance
      ansible.builtin.get_url:
        url: https://kzn34165.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?arch=x86&flavor=default
        dest: "{{ installpathfile }}"
        headers:
          Authorization: Api-Token dt0c01.IRXCHXCACT7DYBUFS6BLZIET.KJBREFFGZ2435RTKUPUMD6Z6J56VTA5G2NWVHXFOETVYAJB236MTZ53TJ4TWD7B6
    - name: Make file executable
      ansible.builtin.file:
        path: "{{ installpathfile }}"
        owner: root
        group: root
        mdoe: '755'
